### ISSUE TITLE
Game stops as opening cutscene starts

### ISSUE THREAD

**Issue by aukondk** [rwengine/openrw#27]
![screenshot_2016-05-20_08-30-11](https://cloud.githubusercontent.com/assets/2167753/15422013/7619aad0-1e76-11e6-86ee-cda10f26806c.png)

Failed to open WAV sound file (invalid or unsupported file)
E [Data] Error loading audio clip /home/aukondk/Games/steamcmd_linux/gta3/audio//lib_a1.wav
E [Data] MP3 Audio unsupported outside cutscenes
E [SCM] Failed to load audio: lib_a1

I checked the WAV file and it plays fine in Audacity and is named correctly (all lower case).

**Comment by TacoDeBoss** [comment]
Works on Linux Mint 17.3 with AMD A8-7410 APU running fglrx 15.3. However the mission starts in the wrong place. You start under the bridge.
![screenshot_2016-05-20_06-18-05](https://cloud.githubusercontent.com/assets/2870898/15428919/05898eca-1e53-11e6-9d96-1fdf21962917.png)

**Comment by TacoDeBoss** [comment]
Reproduced initial bug on Intel/Nvidia setup.
![screenshot_2016-05-20_11-37-41](https://cloud.githubusercontent.com/assets/2870898/15436462/468707e6-1e7f-11e6-9b7b-deace4c652f4.png)

**Comment by PureTryOut** [comment]
Also reproducable on Mesa, Nouveau and proprietary NVIDIA drivers. I thought it happened to everyone, clearly not if you have AMD.

**Comment by christooss** [comment]
AMD Mesa 11.2 reporting in and this is 100% not graphical card issue. But with SFML libraries not processing wav files provided by the game.

**Comment by tsjost** [comment]
Likely a regression in SFML 2.3, which dropped libsndfile in favour of implementing things by themselves (https://github.com/SFML/SFML/pull/757).

Could you confirm your SFML versions, whether it breaks on >=2.3 and works on <2.3?

**Comment by TacoDeBoss** [comment]
Can confirm my laptop is running SFML 2.1. Tomorrow night I will test on my desktop.

**Comment by aukondk** [comment]
I'm using Xubuntu 16.04 and it looks like it uses SFML 2.3.

**Comment by TacoDeBoss** [comment]
Running Debian Sid on my desktop SFML 2.3-2 here.

**Comment by TacoDeBoss** [comment]
Issue is not present on Debian 8.4 Jessie - SFML 2.1

**Comment by TacoDeBoss** [comment]
I can't build the game after downgrading to SFML 2.1 on Debian Sid.. If I get it running I'll post.

**Comment by parkerlreed** [comment]
glew also has to be downgraded to 1.11 since sfml 2.1 links against it. Compile still fails after downgrading both.

````
[100%] Linking CXX executable rwgame
CMakeFiles/rwgame.dir/RWGame.cpp.o: In function `RWGame::globalKeyEvent(sf::Event const&)':
RWGame.cpp:(.text+0xb70): undefined reference to `sf::Image::saveToFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../rwengine/librwengine.a(GameData.cpp.o): In function `GameData::loadAudioStream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
GameData.cpp:(.text+0x1830): undefined reference to `sf::Music::openFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../rwengine/librwengine.a(GameData.cpp.o): In function `GameData::loadAudioClip(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
GameData.cpp:(.text+0x1d17): undefined reference to `sf::SoundBuffer::loadFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../rwengine/librwengine.a(SoundManager.cpp.o): In function `SoundManager::playBackground(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
SoundManager.cpp:(.text+0x55): undefined reference to `sf::Music::openFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
rwgame/CMakeFiles/rwgame.dir/build.make:402: recipe for target 'rwgame/rwgame' failed
make[2]: *** [rwgame/rwgame] Error 1
CMakeFiles/Makefile2:291: recipe for target 'rwgame/CMakeFiles/rwgame.dir/all' failed
make[1]: *** [rwgame/CMakeFiles/rwgame.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
````

**Comment by christooss** [comment]
You can "solve" this if you exchange all wav files in gtainstallfolder/audio with these: https://github.com/christooss/gta3audiofiles/blob/master/audio.zip BEWARE: Make a copy of audio folder before copying anything over it.

These are empty wav files but they play (heh) correctly so game continues to play on. Just without sounds outside the recorded scene.

**Comment by aukondk** [comment]
Processing the wav files through Sound Converter worked for me.

**Comment by tsjost** [comment]
I'm working on replacing SFML's Audio with libsndfile and OpenAL

**Comment by tsjost** [comment]
A fix is now available in the fix/audio branch, please try it out! You should be able to hear 8-Ball say "_I know a place on the edge of the Red Light District where we can lay low_" etc.

More work is needed to get rid of SFML's audio entirely and merge into master.

**Comment by parkerlreed** [comment]
@tsjost 

````
-- Found OpenGL: /usr/lib64/libGL.so  
-- Found OpenAL: /usr/lib64/libopenal.so  
-- Found Bullet: /usr/lib64/libBulletDynamics.so  
-- Found SFML 2.3.2 in /usr/include
-- Found MAD in /usr/include
CMake Error at CMakeLists.txt:71 (find_package):
  By not providing "FindLibSndFile.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "LibSndFile", but CMake did not find one.

  Could not find a package configuration file provided by "LibSndFile" with
  any of the following names:

    LibSndFileConfig.cmake
    libsndfile-config.cmake

  Add the installation prefix of "LibSndFile" to CMAKE_PREFIX_PATH or set
  "LibSndFile_DIR" to a directory containing one of the above files.  If
  "LibSndFile" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
````

````
0 extra/libsndfile 1.0.26-1 [installed]
      A C library for reading and writing files containing sampled sound
1 multilib/lib32-libsndfile 1.0.26-1 [installed]
      A C library for reading and writing files containing sampled sound (32-bit)
````

**Comment by tsjost** [comment]
Thanks, forgot to add the cmake file. Try again now!

**Comment by parkerlreed** [comment]
Thanks, works!

**Comment by tsjost** [comment]
Fix has been merged into master!
